import { PERPLEXITY_API_KEY, PERPLEXITY_MODEL, SUPABASE_URL, SUPABASE_ANON_KEY } from '@env';

export const CONFIG = {
    PERPLEXITY_API_KEY: PERPLEXITY_API_KEY,
    PERPLEXITY_MODEL: PERPLEXITY_MODEL,
    SUPABASE_URL: SUPABASE_URL,
    SUPABASE_ANON_KEY: SUPABASE_ANON_KEY,
};
